version: '3.3'
networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.7.0.0/24

services:
  web:
    image: nginx:latest
    depends_on:
      - php
    working_dir: ${APP_PATH_IN_SERVER}
    labels:
      - gi-web
    container_name: elCamino-nginx
    links:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/var/run/php:/var/run/php/
      - ./:${APP_PATH_IN_SERVER}
    networks:
      vpcbr:
        ipv4_address: 10.7.0.2

  php:
    build:
      context: ./docker/php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
        APP_PATH_IN_SERVER: ${APP_PATH_IN_SERVER}
    volumes:
      - ./:${APP_PATH_IN_SERVER}
      - ./docker/var/run/php:/var/run/php/
      - ~/.composer:/root/.composer
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: ${APP_PATH_IN_SERVER}
    container_name: elCamino-phpfpm
    labels:
      - gi-fpm
    links:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.7.0.3
    extra_hosts:
      - "docker.elcaminofinancial.com:10.7.0.2"
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: elCamino-db
    labels:
      - gi-db
    volumes:
      - ./docker/.data/db:/var/lib/mysql
      - ./docker/mysql/strict-mod-off.cnf:/etc/mysql/conf.d/strict-mod-off.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_DATABASE}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u$MYSQL_ROOT_USERNAME",
          "-p$MYSQL_ROOT_PASSWORD",
          "-h",
          "127.0.0.1"
        ]
      interval: 10s
      timeout: 20s
      retries: 5
    networks:
      vpcbr:
        ipv4_address: 10.7.0.4
